---
- name: Install NTP
  apt: name=ntp state=installed
  tags: ntp

- name: Ensure NTP is enabled and running
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: Install vim
  apt: name=vim state=installed
  tags: vim

- name: Set AllowGroups in /etc/ssh/sshd_config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowGroups"
    line: "AllowGroups {{ ssh_allowed_groups | join(' ') }}"
    insertafter: EOF
    state: present
  notify:
    - restart ssh
  tags: ssh
