---
- name: Install NTP
  apt: name=ntp state=installed
  tags: ntp

- name: Ensure NTP is enabled and running
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: Install vim
  apt: name=vim state=installed
  tags: vim
